stages:
  - unit-test
  - build
  - deploy
  - acceptanceTest
  - destroy

frontend-unit-test:
  stage: unit-test
  image: node
  before_script:
    - cd frontend
  script:
    - npm install
    - npm test -- --watchAll=false
    - cd ..
  artifacts:
    reports:
      junit: frontend/junit.xml
      

build-frontend:
  stage: build
  image: node:16.15.0
  script:
    - cd frontend
    - npm install
    - CI=true npm run build
  artifacts:
    paths:
      - frontend/build

provide-infrastructure-test:
   image: pulumi/pulumi-nodejs
   stage: deploy
   script:
    - cd deployment
    - npm install
    - export PULUMI_ACCESS_TOKEN="$PULUMI_ACCESS_TOKEN"
    - export AWS_ACCESS_KEY_ID="$AWS_ACCESS_KEY_ID"
    - export AWS_SECRET_ACCESS_KEY="$AWS_SECRET_ACCESS_KEY"
    - pulumi login
    - pulumi stack select test
    - pulumi up -y
    - echo $(pulumi stack output bucketUrl) >> test.env
   environment:
     name: test
   artifacts:
     paths:
     - ./deployment/test.env

acceptanceTest:
   image: cypress/base
   stage: acceptanceTest
   script:
     - cd acceptanceTest
     - npm ci
     - export CYPRESS_BASE_URL=http://$(cat ../deployment/test.env)
     - echo $CYPRESS_BASE_URL
     - npm run cypress:run


destroy-infrastructure-test:
  stage: destroy
  image: pulumi/pulumi-nodejs
  script:
    - cd deployment
    - npm i
    - export PULUMI_ACCESS_TOKEN="$PULUMI_ACCESS_TOKEN"
    - export AWS_ACCESS_KEY_ID="$AWS_ACCESS_KEY_ID"
    - export AWS_SECRET_ACCESS_KEY="$AWS_SECRET_ACCESS_KEY"
    - pulumi login
    - pulumi stack select test
    - pulumi destroy -y



