language: node_js
node_js:
  - stable
services:
  - docker
before_install:
- npm i
script: 
  - npm run test:build
  - docker build -t steinko/todofrontend .
  - docker login --username steinko --password RoxyMusic11
  - docker push steinko/todofrontend

