language: node_js
node_js:
- stable

before_install:
- openssl aes-256-cbc -K $encrypted_116c5b5544ce_key -iv $encrypted_116c5b5544ce_iv
  -in appengine-account.json.enc -out appengine-account.json -d
  
script:
- npm install
- npm run-script build
- npm test --ci 
- sonar-scanner

deploy:
  provider: gae
  keyfile: appengine-account.json
  project: project-235906
