apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontendDeployment
  labels:
    app: todo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo
  template:
    metadata:
      labels:
        app: todo
    spec:
      containers:
      - name: frontendComponent
        image: steinko/todoFrontend
        ports:
        - containerPort: 8080