apiVersion: v1
kind: Pod
metadata:
  name: frontend-pod
  labels:
    app: todo-frontend
    env: dev
spec:
  containers:
      - name: todo-frontend-container
        image: docker.io/steinko/todofrontend
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP