apiVersion: v1
kind: Service
metadata:
  name: todo-frontend-service
spec:
  type: NodePort
  selector:
    app: todo-frontend
    env: dev
  ports:
    - port: 9376
      targetPort: 8080
      nodePort: 30010